### ISSUE TITLE
Fake girlfriend task displaying teacher name wrong

### ISSUE THREAD

**Issue by utility2482** [PEDevTeam/PE#21]
#20 
The apostrophe in the code makes the full variable name output instead of the teacher's name. Not sure if there is an easier way of having the apostrophe attached to teacher's name but I inserted a space to temporarily fix the problem.

**Comment by MisterX421138** [comment]
The error you were pointing out was in the link to the task from the bedroom, not the twee file you referenced.  It has been found and fixed.
